# Nome do fluxo de trabalho
name: Build and Push Docker Image

# Gatilho: aciona o workflow em push para a branch 'main'
on:
  push:
    branches:
      - feature/githubactions # Você pode alterar para a branch que desejar, ex: 'develop'

# Variáveis de ambiente para facilitar a manutenção
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Nome da imagem será <seu-usuario>/<seu-repositorio>

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Permissões necessárias para o GITHUB_TOKEN
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

